version: "3.8"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      DB: wesley
      DB_HOST: localhost
      DB_USER: user
      DB_PASS: wesley123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
